# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
lang: ru
url: "https://govorov.online"
baseurl: "" # the subpath of your site, e.g. /blog

title: Николай Говоров
author: Николай Говоров
email: nikolay_govorov@bk.ru
description: Живу в Питере, работаю фронтенд-разработчиком для ВКонтакте
authorBirthDate: 1999-09-24

avatar: https://s.gravatar.com/avatar/72cbf564ef7b21b730ec93a6e3abc9f2

date_format: "%d.%m.%Y"

header_pages:
- index.md
- notes.md

disqus:
  shortname: govorov-online

permalink: /notes/:title/index:output_ext

source: ./website
destination: ./_site

markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable : true

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll/minibundle

exclude:
  - Gemfile
  - Gemfile.lock
  - readme.md
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - node_modules
  - package.json
  - package-lock.json
