backend:
  name: git-gateway
  branch: master

media_folder: static/images
public_folder: /images

collections:
  - name: "notes"
    label: "Note"
    folder: "src/pages/notes"
    create: true
    identifier_field: "name"
    fields:
      - label: "Name"
        name: "name"
        widget: "string"
        required: true

      - label: "Title"
        name: "title"
        widget: "string"
        required: true

      - label: "Publish Date"
        name: "date"
        widget: "date"
        required: true

      - label: "Body"
        name: "body"
        widget: "markdown"
        required: true

  - name: "presentations"
    label: "Presentation"
    folder: "src/pages/presentations"
    create: true
    identifier_field: "name"
    fields:
      - label: "Name"
        name: "name"
        widget: "string"
        required: true

      - label: "Title"
        name: "title"
        widget: "string"
        required: true

      - label: "Date of presentation"
        name: "date"
        widget: "date"
        required: true

      - label: "Video"
        name: "video"
        widget: "string"
        required: true

      - label: "Body"
        name: "body"
        widget: "markdown"
        required: true
